app = "backend-holy-fog-6984"

[build]
  dockerfile = "Dockerfile"

[machines]
  auto_start_machines = true
  auto_stop_machines = true
  min_machines_running = 1

[[services]]
  internal_port = 10000
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls","http"]

  [[services.ports]]
    port = 10000
    handlers = ["http"]

  [services.http_checks]
    path = "/api/health"
    method = "get"
    interval = "15s"
    timeout = "2s"
    grace_period = "10s"
    restart_limit = 0

  [services.concurrency]
    type = "connections"
    soft_limit = 25
    hard_limit = 50
